version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./php.ini:/etc/php/8.3/fpm/conf.d/php.ini
    # 其他可能需要的配置
