version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./wwwroot/SSPanel:/usr/share/nginx/html
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    image: php:8.0-fpm-alpine
    volumes:
      - ./server/php:/var/www/php
    networks:
      - mynetwork

  mysql:
    image: arm64v8/mysql:latest
    volumes:
      - ./server/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
    networks:
      - mynetwork

  redis:
    image: arm64v8/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./server/redis:/data
    networks:
      - mynetwork

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: examplepassword
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
