version: '3.9'

services:
  # Nginx service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./web:/var/www/html
    depends_on:
      - php
    networks:
      - my_app_network

  # PHP service with OPcache
  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./web:/var/www/html
    networks:
      - my_app_network

  # MariaDB service
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - my_app_network

  # Redis service
  redis:
    image: redis:7.0
    container_name: redis
    command: redis-server --requirepass your_redis_password
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
    networks:
      - my_app_network

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - my_app_network

networks:
  my_app_network:
    driver: bridge
