version: '3'

services:
 mysql:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
