version: '3.8'

services:
  nginx:
    image: arm64v8/nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Nginx 配置文件
      - ./server/nginx/certs:/etc/nginx/certs # SSL 证书目录
      - ./website/web1:/usr/share/nginx/html # 网站根目录
    depends_on:
      - php
    restart: always
    networks:
      - mynetwork

  mysql-mariadb:
    image: arm64v8/mariadb:latest
    container_name: mysql-mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=databse_name # 数据库名称
      - MYSQL_ROOT_PASSWORD=root_password # root 密码
      - MYSQL_PASSWORD=database_password # 数据库密码
    volumes:
      - ./server/mariadb:/var/lib/mariadb
    restart: always
    networks:
      - mynetwork

  php:
    image: arm64v8/php:8.2-fpm # 使用你所需要的 PHP 镜像
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./website/web1:/var/www/html # 将网站目录挂载到 PHP 容器中
    depends_on:
      - mysql-mariadb
    restart: always
    networks:
      - mynetwork

  phpmyadmin:
    image: arm64v8/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: "1"
      PMA_HOST: mysql-mariadb
      # PMA_USER: root # 数据库用户 默认root
      # PMA_PASSWORD: 123456 # 数据库密码 默认 123456
    restart: always
    networks:
      - mynetwork

  redis:
    image: arm64v8/redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
