version: '3.8'

services:
  nginx:
    build:
      context: ../server/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - my_network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  mariadb:
    build:
      context: ../server/mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - my_network

  # php:
  #   build:
  #     context: ../server/php
  #     dockerfile: Dockerfile
  #   container_name: php
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   depends_on:
  #     - mariadb
  #   networks:
  #     - my_network

  # redis:
  #   build:
  #     context: ../server/redis
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - my_network

  phpmyadmin:
    build:
      context: ../server/phpmyadmin
      dockerfile: Dockerfile
    restart: always
    environment:
      - PMA_HOST=mariadb # 这里应该是 MariaDB 容器的服务名称
      - PMA_USER=sspanel # 这是你 MariaDB 数据库的用户名
      - PMA_PASSWORD=sspanel-password # 这是你 MariaDB 数据库的密码
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - mariadb
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  nginx-log:
  mariadb_data:
