version: '3.8'

services:
  nginx:
    build:
      context: ../server/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
    volumes:
      - ../server/nginx/certs:/etc/nginx/certs # 映射证书到容器
      - ../server/nginx/nginx.conf:/etc/nginx/nginx.conf # 映射全局配置文件到容器
      - ../server/nginx/sites/server.conf:/etc/nginx/conf.d/nginx.conf # 映射定义配置文件到容器
      - ../web/SSPanel:/var/www/html
      - nginx-log:/var/log/nginx
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  mariadb:
    build:
      context: ../server/mysql
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3306:3306"
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  php:
    build:
      context: ../server/php
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ../server/php/php.ini:/etc/php/8.2/fpm/conf.d/php.ini
      - ../web/SSPanel:/var/www/html
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    # 其他可能需要的配置

  redis:
    build:
      context: ../server/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - my_network

  phpmyadmin:
    build:
      context: ../server/phpmyadmin
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  nginx-log:
  mariadb_data:
