version: '3.8'

services:
  nginx:
    build:
      context: ../server/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
    volumes:
      # - ./nginx-config:/etc/nginx/conf.d
      - nginx-log:/var/log/nginx
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

  mariadb:
    build:
      context: ../server/mysql
      dockerfile: Dockerfile
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  php:
    build:
      context: ../server/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ../server/php/php.ini:/etc/php/8.2/fpm/conf.d/php.ini
    # 其他可能需要的配置

  custom_redis:
    build:
      context: ../server/redis
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

  custom_phpmyadmin:
    build:
      context: ../server/phpmyadmin
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  nginx-log:
  mariadb_data:
