version: '3'

services:
 custom_phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
