version: '3'

services:
 custom_redis:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
