version: '3'

services:
 custom_redis:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null  # 保持容器运行以便进行交互
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
